<?php
/**
 * Home Hero / Swiper.
 *
 * PANEL: add, edit and reorder slides in Home — Slides. Each item controls its
 * title, texts, CTAs, desktop/mobile images, overlay, colors and duration.
 *
 * CODE: the Swiper markup is generated by diniz_studio_hero_slider_shortcode()
 * in inc/render.php. The section visibility/order comes from Home — Seções.
 *
 * @package DinizStudio
 */

$section_id = ! empty( $args['section_id'] ) ? (int) $args['section_id'] : 0;

diniz_studio_render_managed_home_section(
	$section_id,
	'',
	static function () {
		echo diniz_studio_hero_slider_shortcode(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	},
	true
);
